services:
  - type: web
    name: resume-ranker
    env: python
    buildCommand: pip install -r requirements.txt && python -m spacy download en_core_web_lg
    startCommand: gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
